version: '3.8'
services:
  # Java App 服務
  main-app:
  # 1. 這裡的路徑必須跟 deploy.yml 中的倉庫路徑完全一致！
    # 格式: [區域]-docker.pkg.dev/[專案ID]/[倉庫名]/[映像檔名]:latest
    image: asia-east1-docker.pkg.dev/media-processor-492605/media-processor-repo/main-app:latest
    # build: .
    container_name: media_processor_app
    restart: always
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_RABBITMQ_HOST=rabbitmq
      # 將 Profile 改為 prod，強制啟用 GcsStorageService
      - SPRING_PROFILES_ACTIVE=prod
      # GCP建立的 Bucket 名稱
      - GCP_BUCKET_NAME=scott-media-processor-bucket
      # 告訴 Google SDK 我們的金鑰在哪裡
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./media_data:/app/outputs  # 將本機資料夾掛載到 Java 容器內 (備用)
      # 將本機的 JSON 金鑰掛載到容器內！非常重要！
      - ./gcp-key.json:/app/gcp-key.json:ro
    networks:
      - media_processor_network
  # Redis 緩存與任務狀態管理
  redis:
    image: redis:7-alpine
    container_name: media_processor_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - media_processor_network
  
  # RabbitMQ 訊息佇列：處理非同步任務
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: media_processor_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - media_processor_network
  
  # 反向代理：未來的入口
  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
    # ro 代表只讀
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html
      - ./media_data:/usr/share/nginx/html/outputs:ro 
    depends_on:
      - rabbitmq
    networks:
      - media_processor_network

volumes:
  redis_data:

networks:
  media_processor_network:
    driver: bridge