events { worker_connections 1024; }

# http { ... }: 包含所有處理網頁請求的設定
http {
    # 設定上傳檔案大小限制（否則預設只有 1MB，傳圖片會報 413）
    client_max_body_size 20M;

    upstream backend_servers {
        # 直接用 docker-compose 裡的服務名稱，Docker 會自動解析 IP
        server main-app:8080;
    }

    server {
        listen 80;

        # 靜態網頁首頁
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # API 請求轉發給 Java
        location /api/ {
            # 1. 轉發給 Java
            proxy_pass http://backend_servers;
            # 2. 關鍵：保留原始的 Host 資訊
            proxy_set_header Host $host;

            # 3. 關鍵：傳遞真實用戶 IP
            proxy_set_header X-Real-IP $remote_addr;
            # 紀錄請求經過的所有代理 IP。這是一個標準的 HTTP 擴充標頭。
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # 確保 Nginx 不會快取大檔案到硬碟，直接流式傳輸給 Java，預設 Nginx 會先「收完」整個檔案才丟給 Java。設為 off 會讓數據邊傳邊給 Java，能解決傳輸過程中的 Boundary 遺失或超時問題。
            proxy_request_buffering off;
            # 強制使用 HTTP/1.1，因為 1.1 才支援「分塊傳輸 (Chunked Transfer)」，這對上傳檔案更穩定。
            proxy_http_version 1.1;
            
            # 5. 確保標頭不會被過濾(來自 Postman 的 Header（包含 Content-Type 及其 boundary）都原封不動傳遞。)
            proxy_pass_request_headers on;
        }

        # 預留給未來 Nginx 直接讀取靜態圖片
        # 預留給未來 Nginx 直接讀取靜態圖片
        location /outputs/ {
            root /usr/share/nginx/html;
        }

        # WebSocket 連線轉發
        location /ws/ {
            proxy_pass http://backend_servers;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}