spring.application.name=media_processor

# Redis (Docker 映射在 6379)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# RabbitMQ (Docker 映射在 5672)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# 定義 Queue 名稱
app.queue.name=image-process-queue